home_surveillance/home_surveillance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('security_camera.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_surveillance/security_camera/urls.py
from django.urls import path

from . import views

app_name='security_camera'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('upload', views.upload, name='upload'),
    path('recognize', views.recognize, name='recognize'),
    path('search', views.search, name='search'),
    path('delete', views.delete, name='delete'),
    path('update', views.update, name='update'),
    path('webcam_feed', views.webcam_feed, name='webcam_feed'),
    path('viewpic', views.viewpic, name='viewpic'),
]

home_surveillance/security_camera/models.py
from django.db import models

# Create your models here.
class face_dataset(models.Model):
    firstname=models.CharField(max_length=64)
    secondname=models.CharField(max_length=64)
    title=models.CharField(max_length=64)
    reg_date =models.DateTimeField(auto_now_add=True)
    image=models.FileField(upload_to='dataset/')
    def __str__(self):
        return self.firstname + ' ' + self.secondname

class Unknown_dataset(models.Model):
    capture_date=models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='dataset/')
    title=models.CharField(max_length=64, null=True)
class unrecognized(models.Model):
    serial_no=models.IntegerField(null=False, blank=False)
    cap_date=models.DateTimeField(auto_now_add=True)
    status=models.IntegerField(null=True, blank=True)

home_surveillance/security_camera/forms.py
from django import forms
from security_camera.models import face_dataset

class facedatasetForm(forms.ModelForm):
    class Meta:
        model=face_dataset
        fields=('face_name','image')

home_surveillance/security_camera/views.py
from django.shortcuts import render
from gtts import gTTS
from django.core.files.storage import FileSystemStorage
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
import time
from .models import face_dataset
from .models import Unknown_dataset
from .models import unrecognized
import shutil
import dlib
import numpy as np
import os
import cv2
import pickle
import face_recognition
import datetime
from django.db.models import Q
from django.views.decorators import gzip
from django.views.decorators.csrf import csrf_exempt
import pygame
import sys
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMessage
from PIL import Image



#global variables
path='C:\\Users\\HP\\Desktop\\5B\\PROJECT\\face_recognition\\dataset'
homepath='C:\\Users\\HP\\Desktop\\5B\\PROJECT\\face_recognition\\home_surveillance\\security_camera\\static\\security_camera\\Unknown'
class_names =[]

name_encodings_dict={}
VALID_EXTENSIONS = ['.png', '.jpg', '.jpeg']
face_detector = dlib.get_frontal_face_detector()
shape_predictor = dlib.shape_predictor("models/shape_predictor_68_face_landmarks.dat")
face_encoder = dlib.face_recognition_model_v1("models/dlib_face_recognition_resnet_model_v1.dat")



def face_rects(image):
    # convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # detect faces in the grayscale image
    rects = face_detector(gray, 1)
    # return the bounding boxes
    return rects

def face_landmarks(image):
    return [shape_predictor(image, face_rect) for face_rect in face_rects(image)]

def face_encodings(image):
    # compute the facial embeddings for each face 
    # in the input image. the `compute_face_descriptor` 
    # function returns a 128-d vector that describes the face in an image

    return [np.array(face_encoder.compute_face_descriptor(image, face_landmark))
            for face_landmark in face_landmarks(image)]

def nb_of_matches(known_encodings, unknown_encoding):
    # compute the Euclidean distance between the current face encoding 
    # and all the face encodings in the database
    distances = np.linalg.norm(known_encodings - unknown_encoding, axis=1)
    # keep only the distances that are less than the threshold
    small_distances = distances <= 0.45
    # return the number of matches
    k=(sum(small_distances))
    # print(k)
    return sum(small_distances)



def homepage(request):
    cards=face_dataset.objects.all().order_by('-reg_date')
    count=face_dataset.objects.count()
    serialkey=unrecognized.objects.all().order_by('-cap_date')
    context={'cards':cards, 'count':count,'serialkey':serialkey}
    return render(request, 'security_camera/homepage.html', context)

def register(request):
    return render(request, 'security_camera/homepage.html')

def search(request):
    if request.method=='POST':
        try:
            user_name=request.POST['searchname']
            cards=face_dataset.objects.filter(Q(firstname__icontains=user_name) | Q(secondname__icontains=user_name))
            count=face_dataset.objects.count()
            context={'cards':cards, 'count':count}
            return render(request, 'security_camera/homepage.html', context)
        except:
            return HttpResponseRedirect(reverse('security_camera:homepage', ))
        
    return render(request, 'security_camera/homepage.html', context)

def update(request):
    if request.method =='POST':

        personel=face_dataset.objects.get(pk=request.POST['PersonId'])
        with open("C:\\Users\\HP\Desktop\\5B\PROJECT\\face_recognition\\dataset\\encodings.pickle", "rb") as f:
            encodings_database = pickle.load(f)
            encodings_database[request.POST['FirstName'] + ' ' + request.POST['SecondName']] = encodings_database.pop(personel.firstname + ' ' + personel.secondname)

        with open("C:\\Users\\HP\Desktop\\5B\PROJECT\\face_recognition\\dataset\\encodings.pickle", "wb") as f:
            pickle.dump(encodings_database, f)

        old_filename=personel.firstname + '_' + personel.secondname
        new_filename=request.POST['FirstName'] + '_' + request.POST['SecondName']
        old_path = os.path.join(path, old_filename)
        new_path = os.path.join(path, new_filename)

        # Rename the file
        shutil.move(old_path, new_path)
        #update database
        personel.firstname=request.POST['FirstName']
        personel.secondname=request.POST['SecondName']
        personel.title=request.POST['Title']
        personel.save()
       
        return HttpResponseRedirect(reverse('security_camera:homepage', ))

def viewpic(request):
    if request.method=="POST":
        filename=request.POST['serial_no']
        # Open the image file
        image = Image.open(homepath+'\\'+ filename + '.jpg')

        # Show the image
        image.show()
        return HttpResponseRedirect(reverse('security_camera:homepage', ))


def delete(request):
    if request.method=='POST':
        first_target=request.POST['First_Name']
        second_target=request.POST['Second_Name']
        key=request.POST['identifier']
        face_dataset.objects.get(pk=key).delete()
        with open("C:\\Users\\HP\Desktop\\5B\PROJECT\\face_recognition\\dataset\\encodings.pickle", "rb") as f:
            encodings_database = pickle.load(f)
            del encodings_database[first_target + ' '  + second_target] 

        with open("C:\\Users\\HP\Desktop\\5B\PROJECT\\face_recognition\\dataset\\encodings.pickle", "wb") as f:
            pickle.dump(encodings_database, f)
        shutil.rmtree(path + '\\' + first_target + '_'  + second_target)
        return HttpResponseRedirect(reverse('security_camera:homepage'))
        
        
    else:
    
        return HttpResponseRedirect(reverse('security_camera:homepage'))
 



def webcam_feed(request):
    
    
    return render(request, 'security_camera/webcam_feed.html')
    

def upload(request):
    if request.method=='POST':
        FirstName=request.POST['FirstName']
        SecondName=request.POST['SecondName']
        Title=request.POST['Title']
        uploadfile=request.FILES['image']
        username = FirstName + '_' + SecondName
        new=face_dataset.objects.create(firstname=FirstName, secondname=SecondName, title=Title)
        faces=face_dataset.objects.all()
        class_names.clear()
        for face in faces:
            class_names.append(face.firstname + face.secondname)
        
        # print(class_names)
        # print(uploadfile.size)
        # print(uploadfile.name)
        
        fs=FileSystemStorage()
        fs.save(uploadfile.name,uploadfile)
        os.chdir(path)
        New_folder=username
        os.makedirs(New_folder)
        file_path='C:\\Users\\HP\\Desktop\\5B\\PROJECT\\face_recognition\\home_surveillance\\dataset\\' + uploadfile.name
        dir_path=path +'\\'+ New_folder
        shutil.move(file_path, dir_path)
        print(class_names)
        # 
        images_path=dir_path +'\\' + uploadfile.name
        print(images_path)
        image=cv2.imread(images_path)
        encodings=face_encodings(image)
        if encodings:
            name=username.replace('_', " ")
            # get the encodings for the current name
            # e = name_encodings_dict.get(name, [])
            # # update the list of encodings for the current name
            # e.extend(encodings)
            # # update the list of encodings for the current name
            name_encodings_dict[name] = encodings
            print(encodings)
            # with open("encodings.pickle", "wb") as f:
            #     pickle.dump(name_encodings_dict, f)
            #     print('dictionary saved successfully to file')

            try:
                with open("encodings.pickle", "rb") as f:
                    person=pickle.load(f)
                    person[name] = encodings
                
                with open("encodings.pickle", "wb") as f:
                        pickle.dump(person, f)
                        print('dictionary saved successfully to file')

                with open("encodings.pickle", "rb") as f:
                        person=pickle.load(f)
                        print('Person dictionary')
                        print(person)
                
            except:

                with open("encodings.pickle", "wb") as f:
                    pickle.dump(name_encodings_dict, f)
                    print('dictionary saved successfully to file')

                with open("encodings.pickle", "rb") as f:
                        details = pickle.load(f)
                        print('Person dictionary')
                        print(details)
        else:
            shutil.rmtree( path + '\\' + username)
            face_dataset.objects.get(pk=new.id).delete()
            return HttpResponseRedirect(reverse('security_camera:homepage', ))
        
    return HttpResponseRedirect(reverse('security_camera:homepage', ))


def recognize(request):
    try:
        with open("C:\\Users\\HP\Desktop\\5B\PROJECT\\face_recognition\\dataset\\encodings.pickle", "rb") as f:
            encodings_database = pickle.load(f)
    except:
        return HttpResponseRedirect(reverse('security_camera:homepage', ))
        
        
    
    #image = cv2.imread("C:\\Users\\HP\\Pictures\\Camera Roll\\WIN_20230217_09_10_38_Pro.jpg")
    
    cam = cv2.VideoCapture(0)
    process_this_frame = True
    # cam.set(3, 640) # set video widht
    # cam.set(4, 480) # set video height
    # Define min window size to be recognized as a face
    # minW = 0.1*cam.get(3)
    # minH = 0.1*cam.get(4)
    duration =5
    # Get the start time
    start_time = cv2.getTickCount()
    while True:
        _,img =cam.read()
        small_frame = cv2.resize(img, (0, 0), fx=0.25, fy=0.25)
        if process_this_frame:
            # get the 128-d face embeddings for each face in the input image
            encodings = face_encodings(img)

home_surveillance/security_camera/templates/security_camera/homepage copy.html
{% load static %}
<script src="{% static 'security_camera/js/script.js' %}"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'security_camera/js/script.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'security_camera/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/64e7aed880.js" crossorigin="anonymous"></script>
   
    <title>Document</title>
</head>
<body>
     <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
              <nav class="navbar navbar-expand-lg navbar-light bg-gradient-custom " style="box-shadow: 3px 2px 2px rgba(2, 37, 36, 0.5); height:67px;">
                <div class="container-fluid">
                  <a class="navbar-brand text-light" href="#"><h3 class="card-title">SMART CAMERA</h3></a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto">
                      <li class="nav-item">
                        <a class="nav-link text-light" href="#"><h5>Home</h5></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link text-light" href="#"><h5>Notifications</h5></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link text-light" href="#"><h5>Live Feed</h5></a>
                      </li>
                      
                    </ul>
                  </div>
                </div>
              </nav>
              
              

            </div>
        </div>
    </div> 
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <div class="card mb-2 mt-1 bg-body-tertiary " style="height: auto;">
            <div class="card-body pb-0 bg-light">
              <div class="row">
                <div class="col-sm">
                  <h5 class="card-title">FACE DATASET</h5>
                </div>
                <div class="col-sm">
                  <form class="d-flex" role="search" action="{% url 'security_camera:search' %}" method="post">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searchname" required>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form>
                </div>
                <div class="col-sm">
                  <!-- Button trigger modal -->
<button type="button" class="btn btn-success mx-10" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Add
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">NEW FACE</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form class="row g-3" method="post" action="{% url 'security_camera:upload' %}" enctype="multipart/form-data" >
          {% csrf_token %}
          <div class="col-md-6">
            
            <input type="text" class="form-control" placeholder="First Name" aria-label="First name" name="FirstName" required>
          </div>
          <div class="col-md-6">
            
            <input type="text" class="form-control" placeholder="Second Name" aria-label="Second name" name="SecondName" required>
          </div>
          <div class="col-12">
            <input type="text" class="form-control" id="inputAddress" placeholder="Family,friend,colleague" name="Title" required>
          </div>
          <div class="col-12">
            <input class="form-control form-control-lg" id="picture" type="file" name="image" required>
          </div>
         
          
          <div class="col-12">
            <button type="submit" class="btn btn-success">Register</button>
          </div>
        </form>
      </div>
      
    </div>
  </div>
</div>
                </div>
                <div class="col-sm">
                  <button class="btn btn-outline-success" tabindex="-1" role="button" aria-disabled="true">Entries:</button>
                  <button class="btn btn-outline-success" tabindex="-1" role="button" aria-disabled="true">{{count}}</button>
                  <a href="{% url 'security_camera:recognize' %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">Recognize</a>
                 
                </div>

              </div>
                
              </div>
            </div>
          </div>
        </div>
      </div>
  
   
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>

home_surveillance/security_camera/templates/security_camera/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'security_camera/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="container1">
                    <img src="{% static 'security_camera/images/1.jpg' %}" alt="" width="100%" height="800px">
                    <img src="{% static 'security_camera/images/2.png' %}" alt="" width="23%" height="12%" class="logo">
                    <!-- Button trigger modal -->
                        <button type="button" class="btn1" data-bs-toggle="modal" data-bs-target="#exampleModal1">
                             Log in
                        </button>
  
<!-- Modal -->
<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="#" method="post">
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Email address</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <button type="submit" class="btn btn-dark">Log in</button>
              </form>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

  <button type="button" class="btn2" data-bs-toggle="modal" data-bs-target="#exampleModal2">
    Sign up
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <form class="row g-3">
    <div class="col-md-6">
      <label for="inputEmail4" class="form-label">Email</label>
      <input type="email" class="form-control" id="inputEmail4">
    </div>
    <div class="col-md-6">
      <label for="inputPassword4" class="form-label">Password</label>
      <input type="password" class="form-control" id="inputPassword4">
    </div>
    <div class="col-12">
      <label for="inputAddress" class="form-label">Address</label>
      <input type="text" class="form-control" id="inputAddress" placeholder="1234, manhattan">
    </div>
    <div class="col-12">
      <label for="username" class="form-label">Username</label>
      <input type="text" class="form-control" id="inputAddress2" placeholder="">
    </div>
    
    <div class="col-12">
      <button type="submit" class="btn btn-primary">Sign up</button>
    </div>
  </form>
</div>
<div class="modal-footer">
</div>
</div>
</div>
</div>
                </div>
            </div>
        </div>
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>    
</body>
</html>

home_surveillance/security_camera/templates/security_camera/recognizer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Webcam Feed</h1>
    <img src="{% url 'webcam_feed' %}" width="640" height="480">
</body>
</html>

home_surveillance/security_camera/templates/security_camera/webcam_feed.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'security_camera/js/script.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <style>
      body {
        font-family: 'Roboto', sans-serif;
      }
    </style>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'security_camera/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/64e7aed880.js" crossorigin="anonymous"></script>
	<script src=
"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"
	type="text/javascript">

	</script>

	
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
				<nav class="navbar navbar-expand  " style="box-shadow: 3px 2px 2px rgba(1, 27, 26, 0.5); height:67px; width:110%; background-image: linear-gradient(to right, #13274F, #2c3968);">
					<div class="container-fluid">
                  <a class="navbar-brand text-light" href="#"><h3 class="card-title" style=" font-weight: bold;  font-family: 'Roboto', sans-serif;">SMART CAMERA</h3></a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto">
                      <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'security_camera:homepage' %}" style=" font-weight: bold;  font-family: 'Roboto', sans-serif;"><h5>Home</h5></a>
                      </li>
                     
                      <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'security_camera:webcam_feed' %}" style=" font-weight: bold;  font-family: 'Roboto', sans-serif;"><h5>Live Feed</h5></a>
                      </li>
                      
                    </ul>
                  </div>
                </div>
              </nav>
              
              

            </div>
        </div>
    </div> 
   
  
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm">
				<div class="card mt-1" style="width: 100%; height: fit-content;" >
					<h5 class="card-header h3 text-center text-light bg-primary " style="box-shadow: 3px 2px 2px rgba(2, 37, 36, 0.5)">
						LIVE STREAM
					</h5>
					<div class="card-body mx-auto " >
						<div class="booth" style="box-shadow: 3px 2px 2px rgba(2, 37, 36, 0.5)">
							<video class="mx-auto" id="video" width="auto"
								height="auto" style="box-shadow: 3px 2px 2px rgba(2, 37, 36, 0.5)" autoplay>
							</video>
						</div>

						<div class="text-right">
							<a href="#!" class="btn btn-danger"
								onClick="stop()">
								Stop Cam
							</a>
							<a href="#!" class="btn btn-success"
								onClick="start()">
								Start Cam
							</a>
						</div>
					</div>
				</div>
			</div>
            <div class="col-sm">
				<div class="card mt-1" style="width: 100%; height: fit-content;" >
					<h5 class="card-header h3 text-center text-light bg-success " style="box-shadow: 3px 2px 2px rgba(2, 37, 36, 0.5)">
						LIVE STREAM
					</h5>
					<div class="card-body mx-auto " >
						<div class="booth" style="box-shadow: 3px 2px 2px rgba(2, 37, 36, 0.5)">
							<video class="mx-auto" id="video1" width="auto"
								height="auto" style="box-shadow: 3px 2px 2px rgba(2, 37, 36, 0.5)" autoplay>
							</video>
						</div>

						<div class="text-right">
							<a href="#!" class="btn btn-danger"
								onClick="stop1()">
								Stop CAM
							</a>
							<a href="#!" class="btn btn-success"
								onClick="start1()">
								Start CAM
							</a>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>

	<script>
		var stop = function () {
			var stream = video.srcObject;
			var tracks = stream.getTracks();
			for (var i = 0; i < tracks.length; i++) {
				var track = tracks[i];
				track.stop();
			}
			video.srcObject = null;

		}
		var stop1 = function () {
			var stream = video.srcObject;
			var tracks = stream.getTracks();
			for (var i = 0; i < tracks.length; i++) {
				var track = tracks[i];
				track.stop();
			}
			video.srcObject = null;

		}
		
		var start = function () {
			var video = document.getElementById('video'),
				vendorUrl = window.URL || window.webkitURL;
			if (navigator.mediaDevices.getUserMedia) {
				navigator.mediaDevices.getUserMedia({ video: true })
					.then(function (stream) {
						video.srcObject = stream;
					}).catch(function (error) {
						console.log("Something went wrong!");
					});
			}
		}
		var start1 = function () {
			var video = document.getElementById('video1'),
				vendorUrl = window.URL || window.webkitURL;
			if (navigator.mediaDevices.getUserMedia) {
				navigator.mediaDevices.getUserMedia({ video: true })
					.then(function (stream) {
						video.srcObject = stream;
					}).catch(function (error) {
						console.log("Something went wrong!");
					});
			}
		}
		// $(function () {
		
		// 	start1();
		// });
	</script>
</body>

</html>